name: TVRemoteApp
options:
  bundleIdPrefix: com.tvremote
targets:
  TVRemoteApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - .
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tvremote.TVRemoteApp
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
      SWIFT_VERSION: "5.0"
      ENABLE_DEBUG_DYLIB: YES
